### PR TITLE
No longer pollute stdout during searches

### PR DESCRIPTION
**Pull request by nitrix**
Hello,

I'm using your library and you did an awesome job. :)

During my usage, I noticed processResponse is polluting stdout with debugging information.
This is good for an application but not so much so for a library.

I made a quick change to remove the offending line.

Cheers,
Alex

### CODE REVIEW

**Comment by nitrix** [comment]
What is your opinion on this? I'm maintaining a fork in the mean time.

**Comment by dlasky** [comment]
yeah this was a mistake, can you remove the gitignore changes though? i'd prefer not to have any goland config committed accidentally

**Comment by nitrix** [comment]
Okay. I removed the `.idea` rule in `.gitignore` that I had added.

Though, this will have the opposite effect of what you described. Now Git is allowing again GoLand configs to get committed.

I don't know if that's a misunderstanding or communication issue.

**Comment by dlasky** [comment]
Posting before coffee

**Review by dlasky — APPROVED** [review]

**Comment by dlasky** [comment]
you are definitely correct, i swore it was in there already which i think is how my brain tricked me.

In any case thanks a ton for the fixes and apologies again for the huge delay, somehow i had this repo unwatched :(

**Comment by nitrix** [comment]
No problem! I was maintaining my own fork in the mean time. :)

We got everything merged upstream, I updated my dependencies and the fork is gone. https://github.com/nitrix/alive/commit/2f267ad4b32d6301efcd7f56410c983ff2acb6b5

Cheers,
Alex.

**Comment by dlasky** [comment]
oh cool project, you should add sway support!

**Pull request merged**
